-- Create DOrSU News table for caching scraped news articles
-- This provides faster loading and offline access to news content

CREATE TABLE IF NOT EXISTS public.dorsu_news (
    id BIGSERIAL PRIMARY KEY,
    news_id VARCHAR(100) UNIQUE NOT NULL, -- Unique identifier from scraper
    title VARCHAR(500) NOT NULL,
    summary TEXT,
    image_url TEXT,
    date TIMESTAMPTZ NOT NULL,
    author VARCHAR(100) NOT NULL DEFAULT 'DOrSU-PIO',
    read_more_url TEXT NOT NULL,
    scraped_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_dorsu_news_date ON public.dorsu_news(date DESC);
CREATE INDEX IF NOT EXISTS idx_dorsu_news_news_id ON public.dorsu_news(news_id);
CREATE INDEX IF NOT EXISTS idx_dorsu_news_active ON public.dorsu_news(is_active);
CREATE INDEX IF NOT EXISTS idx_dorsu_news_scraped_at ON public.dorsu_news(scraped_at DESC);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_dorsu_news_updated_at 
    BEFORE UPDATE ON public.dorsu_news 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE public.dorsu_news ENABLE ROW LEVEL SECURITY;

-- Create policies for news access
-- Allow read access to all authenticated users
CREATE POLICY "Allow read access to news for authenticated users" ON public.dorsu_news
    FOR SELECT USING (auth.role() = 'authenticated');

-- Allow insert/update for service role (for API scraping)
CREATE POLICY "Allow insert/update for service role" ON public.dorsu_news
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

-- Add comments for documentation
COMMENT ON TABLE public.dorsu_news IS 'Cached DOrSU news articles from website scraping';
COMMENT ON COLUMN public.dorsu_news.news_id IS 'Unique identifier generated by scraper based on title and date';
COMMENT ON COLUMN public.dorsu_news.title IS 'News article title';
COMMENT ON COLUMN public.dorsu_news.summary IS 'Brief summary or excerpt of the article';
COMMENT ON COLUMN public.dorsu_news.image_url IS 'URL to the news article image';
COMMENT ON COLUMN public.dorsu_news.date IS 'Publication date of the news article';
COMMENT ON COLUMN public.dorsu_news.author IS 'Author or source of the news article';
COMMENT ON COLUMN public.dorsu_news.read_more_url IS 'URL to the full article on DOrSU website';
COMMENT ON COLUMN public.dorsu_news.scraped_at IS 'Timestamp when the article was scraped';
COMMENT ON COLUMN public.dorsu_news.is_active IS 'Whether the news item should be displayed (soft delete)';